### ISSUE TITLE
Error in Line 31 of allureReport export

### ISSUE THREAD

**Issue by narayananpalani** [maritome/cypress-msteams-reporter#2]
When running the command as npx cypress-msteams-reporter, it throws error at line 31 of allure-reporter js file. It means ,the plugin fail to read application and version details from environment.properties which is already placed insure allure report folder.

**Comment by maritome** [comment]
Hello @narayananpalani! You should create the environment.properties file on the **allure-results** folder. Then when you generate your allure report everything needed by the plugin will be automatically on your **allure-report** folder. 
Let me know if this clarification helps solving your problem. If not, then please send me the logs. I need to see the error that the plugin throws, to be able to investigate the issue.

**Comment by narayananpalani** [comment]
Option of adding environment.properties has been tried already but no luck on getting the reports towards ms-teams.will try again to capture the logs and share it here in few days time.

**Comment by maritome** [comment]
Hello @narayananpalani! The reported issue is related to the Node.js version. Please, check your node version and upgrade it to v14.
