### ISSUE TITLE
Issue with Cypress integration

### ISSUE THREAD

**Issue by anubajaj23** [maritome/cypress-msteams-reporter#3]
Hi,

I am not able to integrate this package with Cypress. Getting an error 'Unexpected token '.'' while running 'npx cypress-msteams-reporter'

Steps what i followed:
- I have my prerequisite installed and working fine i.e Allure/commandline
- npm install cypress-msteams-reporter --save-dev
- Created a .env file and added MS Hook in the root of directory
- Created environment.properties under allure-results folder.

But still not able to integrate properly. Can anyone please help me out on this ?
I even couldn’t find any example or documentation, Can you please guide me?

Cypress Version: 6.5

**Comment by MaxIrv** [comment]
Having the same issue as above, were you able to find a solution?

**Comment by RuslanAisin** [comment]
the same problem 
MS Teams message was sent successfully.
(node:4404) UnhandledPromiseRejectionWarning: Error: Incoming webhook URL is required
but no massage posted

**Comment by anubajaj23** [comment]
You probably forgot to provide Incoming webhook URL in .env file. Please do this setup for this. This should work then.

But in my case its not calling MsTeams package, saying unexpected token. Are you facing same issue ?

**Comment by RuslanAisin** [comment]
> You probably forgot to provide Incoming webhook URL in .env file. Please do this setup for this. This should work then.
> 
> But in my case its not calling MsTeams package, saying unexpected token. Are you facing same issue ?

I have created .env but doesnt work. After that I insert webhook in node_modules\cypress-msteams-reporter\src\ms-teamsWebhook.js. After that message will appear in chat but witout button allure
![image](https://user-images.githubusercontent.com/49075028/119156070-88cfa800-ba5c-11eb-9351-cdfda0df9206.png)

**Comment by maritome** [comment]
> Hi,
> 
> I am not able to integrate this package with Cypress. Getting an error 'Unexpected token '.'' while running 'npx cypress-msteams-reporter'
> 
> Steps what i followed:
> 
> * I have my prerequisite installed and working fine i.e Allure/commandline
> * npm install cypress-msteams-reporter --save-dev
> * Created a .env file and added MS Hook in the root of directory
> * Created environment.properties under allure-results folder.
> 
> But still not able to integrate properly. Can anyone please help me out on this ?
> I even couldn’t find any example or documentation, Can you please guide me?
> 
> Cypress Version: 6.5

Hello @anubajaj23! I could reproduce this case only when using an incorrect incoming webhook url. Can you please double check your url and let me know if the problem still persists.

**Comment by RuslanAisin** [comment]
Hello @maritome ! Thank you for help! I write .env correctly and it works perfectly.

Let me ask one more qusetion about 'Open Test Report' 
I type:
```
npx cypress-msteams-reporter --report-url "http://127.0.0.1:5500/allure-report/" --verbose
reportPath: ./allure-report/widgets/status-chart.json
 testEnvironmentPropertiesFile: ./allure-report/widgets/environment.json
 reportUrl: http://127.0.0.1:5500/allure-report/
MS Teams message was sent successfully. 
```
whats ok I receved msg and see button. But when I click I see another URL like "https://teams.microsoft.com/null"
another one test I have changed  --report-url "https://google.com" it works correctly. Google page opens
Whats wrong with allure url?

**Comment by anubajaj23** [comment]
Hi @maritome,

I have configured Incoming webhook URL correctly because i have verified it multiple times, but after debugging i found the issue is with some packages. Please see the screenshots

<img width="927" alt="Screenshot 2021-05-24 at 3 55 10 PM" src="https://user-images.githubusercontent.com/51432815/119334437-c163c180-bca8-11eb-8a30-22b086b63dc9.png">

<img width="613" alt="Screenshot 2021-05-24 at 3 55 22 PM" src="https://user-images.githubusercontent.com/51432815/119334472-c9236600-bca8-11eb-8d87-4b7377b9f1fe.png">


I am using TS with this project, is there any dependencies that i m missing? 

Also i have some doubt with my **plugins/index.js** file, i am using dotenv with allure plugin, what will be the correct way to initialise both together?

Can you please help me on this ?

**Comment by maritome** [comment]
Hello @anubajaj23,
Sorry for the late response. 
It seems like the reported issue is related to the Node.js version. Can you please check your node version and if it is v12 upgrade it to v14? 
I tried with node v14.17.0 and it works fine for me.
