### ISSUE TITLE
button "Open Test Reoprt" don't appear 

### ISSUE THREAD

**Issue by RuslanAisin** [maritome/cypress-msteams-reporter#4]
If I combine couple npm command in package.json like
```
"scripts": {
   "posttest": "npm run allure:report && (npx cypress-msteams-reporter --report-url 'http://localhost:5500/allure-report/index.html' --verbose)",
}
```
and write npm run posttest, I didnt see the button in MS Teams
Maybe I use bad practice?

**Comment by RuslanAisin** [comment]
up

**Comment by guthizon** [comment]
Hi @RuslanAisin , try:
 "scripts": {
   "posttest": "npm run allure:report && (npx cypress-msteams-reporter --report-url http://localhost:5500/allure-report/index.html --verbose)",
}

Remove the quotes from the url.

**Comment by RuslanAisin** [comment]
Hello @guthizon, thank you for advice. It is working properly,
